
environment: dev
java:
    options: -Xms64m -Xmx128m -XX:PermSize=32m -XX:MaxPermSize=64m -XX:+UseG1GC -Djava.security.egd=file:/dev/urandom
zipkin: 
    enabled:  false
    url: zipkin.zipkin.svc.cluster.local
carts:
    enabled: true
    image: weaveworksdemos/carts
    version: 0.4.8 
    database:
        image: mongo
        persistence:
            enabled: false
            # recommended --> false
            size: 1Gi
            storageclass: "" 
orders:
    enabled: true
    image: weaveworksdemos/orders
    version: 0.4.7
    persistence:
        enabled: true
        size: 1Gi
        storageclass: "" 
    database:
        image: mongo
        persistence:
            enabled: false
            # recommended --> false
            size: 1Gi
            storageclass: "" 
catalogue:
    enabled: true
    image: weaveworksdemos/catalogue
    version: 0.3.5
    database: 
        image: weaveworksdemos/catalogue-db
        version: 0.3.0
        persistence:
            enabled: true
            size: 1Gi
            storageclass: "" 
user:
    enabled: false
    image: weaveworksdemos/user
    version: 0.4.4
    database: 
        image: weaveworksdemos/user-db
        version: 0.3.0
        persistence:
            enabled: true
            size: 1Gi
            storageclass: "" 
queuemaster:
    enabled: false
    image: weaveworksdemos/queue-master
    version: 0.3.1
rabbitmq:
    enabled: false
    image: rabbitmq
    version: 3.6.8
sessiondb:
    enabled: false
    image: redis
    version: alpine 
shipping:
    enabled: false
    image: weaveworksdemos/shipping
    version: 0.4.8 
    persistence:
        enabled: true
        size: 1Gi
        storageclass: "" 
payment:
    enabled: false
    image: weaveworksdemos/payment
    version: 0.4.3
frontend:
    image: weaveworksdemos/front-end
    version: 0.3.12
    replicas: 1
loadtest:
    replicas: 2
    enabled: false
