apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: catalogue-db-secret
  namespace: dev
spec:
  encryptedData:
    MYSQL_DATABASE: AgBer4+QSWh01PqZ3y+vpLHKPdWKDUy25INerz7ZEkAF0QLQaLK44bfPKXEqpJbOgIKK9HthxSTd/dQAoLobFmfyMNmgrVVc3Ygz8BlT1Us572ZpeIOcxeuAaMO64mk+14OkhBM7B5VbClTIUapY6QSOZOgeQBFxFoq9YCC2/CU1aUV4L2Pe45wu+o0BuINxB+8Zb7OHjOh4BTkRcClFH6Q8mbUFlfzYT/jlhkxcK1SLubd2ijaamCU1Ui9ZzWhFtWEnqy6ACoSOgEN4aWqxfTg8mM3WNGt5mfWlinO46UikIp9fD+vw/Vc6V98Y9rPP58Cno56qAFo1pK1WML4sOFMZ/n0/MUvyC5nI8H/NhqphlDzEPdPMiLvY6SyW0ymtEWpnOU1aluFlvM50sUACYKcV8sZgBHRPolploV5m+uYFWPmpfyFiHM85vCHujQrrrzzhVN2EK+7mwg9+p3iUK8g63HGMV14VmBKYdoimPLj83eA+PD898cXSrWP2LBxawLdLLUjkBkf2C1Tt0KSLrHBf/SJfotidilGmvn9yoMHBfYTkfwpsbB3aSso4riTcNZru44XkVGkM6+qZGkLarDId3c+EgtowmacSCoDmlGsfIUBe7U63V/B5QbhAREVpkLo+/yl9J3d+9LYYXE0+hhKCEq+f5LKKBR9dFuukFifCyX5XoDNgHc7a+fECpg2KT3AWVYe90omM
    MYSQL_ROOT_PASSWORD: AgCAVGD1eT0NE4h91ZGyTHH0iI/grEn+Zj5TnAAnC2VjUmpGDbY6MvmVxQ52WUeFRHh+jhNMkmY/wjolrTKYdHFuGY5Qz0Xh+sBs+MYvTYvOBfAdP4Hzw/ysdc6bvHXVD8+iP7rJU2KmdU/U1nIatRFp92nIxOdzDB3vASGJhWclWlPgSWEwgUCXi3tCVfkjWXG+/a0CB6gGgV3hGS2kMzy04smgbExNVpPMYS1gBXu1KU9nSugCUqZw5c/JpQ8QzZYzsSHbaRgTJ6GYuCD8s/6z7XS7YNCVcWJr8skj9tql/zf85OsAyn6WCaiJK+Q53DN8KBIVl+ixgSMd/BwBjA1GXsRg6bfaAgwq7PcW/pzM276G1i1PRWBuLzkxKMz2UMTgnraesRfJOyE27aoZDX1xaDlu0jv/61xzUwUQ8g2rl71epSYm/Avgudy7STW/PH18RY50/5bYuOTJQ1tVdVfzaJ5z/HVsYjoaoeAbrRfp9wSTpOx3D/chS9OthGQrdbOio3n4C/qk8rEZoEBwpktQBLJFpAv2U3ajTYv/HSYxWKn7Kh+ZwkDbA0d/C6pDPhxCk3Q4NjHYUuJ83ulrFo6PwclchcZqNJDTiSXN6clgppbnEW27Y/zzt9IazT4PexpO2giB2FNxDLSP6CiiQ5+/70M5L5ppeyAzdiYTN90V4PD5AwFa4wF6NYDXF9dv4IG9cs6bz5h3oLMffJj3
  template:
    metadata:
      creationTimestamp: null
      name: catalogue-db-secret
      namespace: dev

