apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: socks-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/auth-realm: "Authentication Required - ok"
    nginx.ingress.kubernetes.io/auth-secret: "alteos-auth-{{ .Values.env }}"
    nginx.ingress.kubernetes.io/auth-type: "basic"
spec:
  rules:
    - host: "socksmarket-{{ .Values.env }}"
      http:   
        paths:
        - path: /
          backend:
            serviceName: front-end
            servicePort: 80
  tls:
   - hosts: 
     - "socksmarket-{{ .Values.env }}"
     secretName: "tls-secret-{{ .Values.env }}"  

   

    
    
