{{- if .Values.orders.enabled }}
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: orders-db
  labels:
    name: orders-db
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: orders-db
    spec:
      {{- if .Values.orders.database.persistence.enabled }}
      securityContext:
        runAsUser: 999
        runAsGroup: 999
        fsGroup: 999
      {{- end }}
      containers:
      - name: orders-db
        image: {{ .Values.orders.database.image }}
        ports:
        - name: mongo
          containerPort: 27017
        securityContext:
          capabilities:
            drop:
              - all
            add:
              - CHOWN
              - SETGID
              - SETUID
          readOnlyRootFilesystem: true
        volumeMounts:
        - mountPath: /tmp
          name: tmp-volume
      volumes:
        - name: tmp-volume
        {{- if .Values.orders.database.persistence.enabled }}
          persistentVolumeClaim:
            claimName: ordersdb-pvc
        {{- else}}    
          emptyDir:
            medium: Memory 
        {{- end }}
{{- end }}
