apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: catalogue-db-secret
  namespace: dev
spec:
  encryptedData:
    MYSQL_DATABASE: AgBVuWyTCuibkUnOhJEj8upqyxLm3Kg451rUA9L/tVPKpsIagO6HivESTXFKX/N4wmw2hZYtT+/JQnSsA4iTBxcx2XsIF7zA+vQfSb5AdTySvYBb/6ZcRGxfLZ82XE1AcCi8BZs0xDONcDJS0lqn3E+lxzEAgN7/aIaLVgqpTUcgf/qHc46XrDOSuTT8ddgx8/vnH6TTP6Qd9grRRWat0+9ZPPDylBwMHWxU5W7Tphk9N9PF+YUfvQRWK/tVD1bxHNZzTjeOu9beNcqlArh1HneFCN7uSB3kD3XWv/FINI+N6PtV01CYPSnfIrdLMi1xU9UW1A6cpS6yw7aXj0ICmdtQPT+qGYFPZ49pxtAw9R/SlJNL3aHZ2DTJ2g2maIJ4fPsoX0xWlobYmZd1pZr+rvPRIh3GSTpVlMxbbdRLLNDHLjaRWKjm1kYBf8pRiyuyFALj43mkQ3J538lyXPOM9jX63vCK52l64aZlgwBFQ5BQQuzv2Xdw01Ot1n0QNLkX+4bZWgHERt8+piV40wzf/LRZJuBXVlTFZrhGKuZrX2wxZgGJoyQxvAyqCO+B95/dSpmIBFdwpiOvuksZCAYwCmcZpmP5FGgEQgoA2xlYvQcArNMh0in2PyIIvsFHjVT5OG6pvwyEQEJhXuviIaH2PzMaEskCdBo74amvyNbHd2+0wNIvMBe0WcKKdI203JQ6YV7lihfMOFfh
    MYSQL_ROOT_PASSWORD: AgA41Lk8zkrRrrlPrb7mfelVQMWocWmPtOdxUZrsSBKW31ACwOs2OpffAF8s0+qDiNJSVBjVaMQRQQCIFbfQszVri8sjbzssud5px6jHeJwHFI+kTktvtcZxedxeghzRzUkBBy9NNTxVlBIrguh2rMLODKHCEM9CrgGitC42tw4YjoWGvqtKQGW3RV0eftO+B4RQH/v/Pr7QJhNidnuvYIiUPSLhujLm2/kaFfRq7wWyBhWMx8Py+1pSx8qPLJwZ/uG6cftBII9ltoK4g04/sVwT/oJ23+FZVdDT9UhqK/RpHpq9JqM/y1El2vpef6Xt72OSmPL0cTscOkdpwKA9tH5X3mQYo7cKeBquK8ImYptHeAplNbYkV0Y16tTrE/LuJGylF1Fc2Ij6a7KKCJ8SAIURy63pfm6A77RKF201ucavguE0dLyg3//l1erUk5irrbPn6t5KZNnQx66HnzmxshSQtqkfYJWVOx8BgszK9ans3mgfRQ6oKmbTZPStSk88VB4510YuLwZSAYXaOfHwOqQD3aL7uKZHzFNIliANdLCF2X3OKK+/+wUVCyh6g9/lxLrJZMKMXTwYk9rlH0ni5/Y6n6XPERNX2wQfI/S6ljdtzxFkodlSowqz0k7wSedZ4s9YUmYj2JD06/i+wVtsY5Pf16qdnSIkq8vjnz/4ld9Po2vo4TMK1mSEGYqrK5Nu9+NDFrmE8OXK3YeMeHl0hg==
  template:
    metadata:
      creationTimestamp: null
      name: catalogue-db-secret
      namespace: dev
    type: Opaque

