apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: catalogue-db-secret
  namespace: dev
spec:
  encryptedData:
    MYSQL_DATABASE: AgBttt++fJub4UGCDFUA/sn63WHohV8fT2AkBhWeTdeya09qZC+3FrPnakuewTkW7PpxxENyWGDPTYdyRw1FLtJte8E8/u/IRFFUIC74EDRr14eboiUSBrzbw89G2k9wpCUG6vbfyazT4koA2PAUFv07DZB8KwsTtWwqxKoCHYvQL6SCEvkjDP5kEHPP2bGuyoRuYG445yxO7RgNXONybZByaXn/zLZcHcaj1uk9IDWil4Egc8tCqyTkjH60GeMe7cVdLz98E9csmXrQYVHcqgoG48Cxluis99UTI8wjiFKQpAFe5Sz65RiiKuc6utpROmi5xRVHtqnNASKtJz8r/8sXbT4KMYDQyquiXEmIRMogLtm085JD68wyEBREfSB3LlG1+6Myj5x64GCsGfOmb5TcKTitY179WoiSLXu1WkMrA9ATPsUmpnU7Lvl9vybyym9Ue2j9KINjLf6X58k09I/N5eBrs0xNUa6PF3CqNagh23pBR7DTPG8O+sBm8Q1S8cOGlHVF4MdoiLggolcCCgjJgmgJqlwBi/jPa679z5yIAC4B5z4jfeZa6pUrlNI2oVTO1VYN6xoxPbkN/Q23pCQvCfRb8yGMlY432B1JNk/G58rVsbn15jewp0h4r1tc1FpqhyN5Fj6WFCIKZfuK5CQ6BfqNr8Nnizv1j9P9pAGjH86XHeFSv0QBmsIATf3AOuvZkbt5lDJ0
    MYSQL_ROOT_PASSWORD: AgDNklkZGgtuKvPhvJTfhpnQWp3kTV290EWep+uLo8AE2SgeSzkKukFpEW0AMY32XyaS6yC8cnqWzepnFgTbGLrSysIdjh6hBUrKg232nM9SNLcJ193LM1hrKOKQY/3B/5tzo0pvFISca7zp1MYpRM6alx2XQoCNTKgWXlUJn13kQjrszvEX6esfY3hAke1+cW+TzryyIs3OeYXan6k+weN02jf0WrGbqUrdy9fKK8ztU4Sq6vOpmct1tmH8MGUaeI4m37Bd0G4SSIDsy4zPjtOEHZ/SKPzwwyUmeT80Z9tjGtWjlyKdvo1F6iNqIOXI1D6Dt9c39h57H6bIwFsg85YASQ/fWTQLTwifXuOHeQtO1cYz04uI2hohvCHmhiYkZ6aZMESVBSdd/F5mrlY0DlBeiicI0FID409QMGPbBehA5ROLenQuKNEKrZZmB7uVwWlg/Ar0Wyy76U36LCkPlXSs5lE4aGsuvrzTp4AFNwUDsIfK92ti9Vi4ydo6aydiR4nHJVwkZI7o0fgovERyN5XJgdbBsusaWN3VCDGD9/Q/E9EnHa0XUkEfIsxg4jcagRDGEupyhnkQtyOH8Wa+HKvxEy5av8BBsP6TpXOn6Dw0Pss1F2pY0IlAHjAROQgetE+upFuEUgz3lIR43XjlJs7MyJXJOeWChiLC8S4G7R7sh3A7x7p4so736pGU1NSpvynL3c8GnJ4Chm5EYqtmHw==
  template:
    metadata:
      creationTimestamp: null
      name: catalogue-db-secret
      namespace: dev
    type: Opaque

