{{- if .Values.user.enabled }}
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: user-db
  labels:
    name: user-db
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: user-db
    spec:  
      {{- if .Values.user.database.persistence.enabled }}
      initContainers:
      - name: chmoder
        image: alpine:3.6
        command:
        - chown
        - -R  
        - 999:999
        - /tmp
        volumeMounts:
        - name: tmp-volume
          mountPath: /tmp
      {{- end }} 
      containers:
      - name: user-db
        image: {{.Values.user.database.image }}:{{.Values.user.database.version }}

        ports:
        - name: mongo
          containerPort: 27017
        securityContext:
          capabilities:
            drop:
              - all
            add:
              - CHOWN
              - SETGID
              - SETUID
          readOnlyRootFilesystem: true
        volumeMounts:
        - mountPath: /tmp
          name: tmp-volume
      volumes:
        - name: tmp-volume
          {{- if .Values.user.database.persistence.enabled }}
          persistentVolumeClaim:
            claimName: userdb-pvc
          {{- else}}    
          emptyDir:
            medium: Memory 
          {{- end }}
{{- end }} 
