{{- if .Values.zipkin.enabled -}}
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: zipkin
  labels:
    name: zipkin
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: zipkin
    spec:
      containers:
      - name: zipkin
        image: openzipkin/zipkin
        ports:
        - containerPort: 9411
        envFrom:
          - secretRef:
              name: zipkin-secret
{{- end -}}
