{{- if .Values.zipkin.enabled -}}
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: zipkin-cron
  labels:
    name: zipkin-cron
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: zipkin-cron
    spec:
      containers:
      - name: zipkin-cron
        image: openzipkin/zipkin-dependencies:1.4.0
        envFrom:
          - secretRef:
              name: zipkin-secret
        command: ["crond"]
        args: ["-f"]
{{- end -}}
